# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# GENERATED FILE - DO NOT EDIT.
# ruff: noqa: E501  (registry ids set the line length; not ours to wrap)
#
# Regenerate after any model/ edit:
#   weaver registry generate -r src/nemo/lens/semconv/model -t templates \
#     python <out>   &&   cp <out>/attributes.py src/nemo/lens/semconv/_generated/
#
# tests/test_semconv_generated.py fails if this drifts from model/.
"""Attribute-name constants, generated from ``semconv/model/``.

``semconv/attributes.py`` re-exports these and owns the non-attribute
``SEMCONV_VERSION``. Edit the model, not this file.
"""

DL_BATCH_SIZE = "dl.batch_size"
DL_DATA_PARALLEL_RANK = "dl.data_parallel.rank"
DL_DATA_PARALLEL_SIZE = "dl.data_parallel.size"
DL_GRAD_NORM = "dl.grad_norm"
DL_ITERATION = "dl.iteration"
DL_LEARNING_RATE = "dl.learning_rate"
DL_LOSS = "dl.loss"
DL_MICROBATCH_ID = "dl.microbatch_id"
DL_PIPELINE_PARALLEL_RANK = "dl.pipeline_parallel.rank"
DL_PIPELINE_PARALLEL_SIZE = "dl.pipeline_parallel.size"
DL_SEQUENCE_LENGTH = "dl.sequence_length"
DL_TENSOR_PARALLEL_RANK = "dl.tensor_parallel.rank"
DL_TENSOR_PARALLEL_SIZE = "dl.tensor_parallel.size"
DL_THROUGHPUT_TFLOPS = "dl.throughput_tflops"
DL_THROUGHPUT_TOKENS_PER_SEC = "dl.throughput_tokens_per_sec"
GENAI_OPERATION_NAME = "gen_ai.operation.name"
GENAI_PROVIDER_NAME = "gen_ai.provider.name"
GENAI_REQUEST_MODEL = "gen_ai.request.model"
GENAI_TOKEN_TYPE = "gen_ai.token.type"
GYM_NUM_SERVERS = "gym.num_servers"
GYM_ROLLOUT_BATCH_SIZE = "gym.rollout.batch_size"
GYM_SERVER_NAME = "gym.server.name"
GYM_SERVER_TYPE = "gym.server.type"
GYM_VERIFY_SUCCESS_RATE = "gym.verify.success_rate"
HOST_NAME = "host.name"
INVERTED_DELTA_SECONDS = "inverted.delta_seconds"
INVERTED_END_EPOCH_SECONDS = "inverted.end_epoch_seconds"
INVERTED_SKEW = "inverted.skew"
INVERTED_START_EPOCH_SECONDS = "inverted.start_epoch_seconds"
K8S_CONTAINER_NAME = "k8s.container.name"
K8S_JOB_NAME = "k8s.job.name"
K8S_NAMESPACE_NAME = "k8s.namespace.name"
K8S_NODE_NAME = "k8s.node.name"
K8S_POD_NAME = "k8s.pod.name"
K8S_POD_UID = "k8s.pod.uid"
NEMO_RUN_ID = "nemo.run.id"
NEMO_SPAN_TRUNCATED = "nemo.span.truncated"
NEMO_USER_ID = "nemo.user.id"
NV_DL_JOB_UUID = "nv.dl.job.uuid"
NV_DL_LAUNCH_CONTAINER_IMAGE = "nv.dl.launch.container.image"
NV_DL_LOCAL_RANK = "nv.dl.local_rank"
NV_DL_PROVIDER_NAME = "nv.dl.provider.name"
NV_DL_RANK = "nv.dl.rank"
NV_DL_ROLE = "nv.dl.role"
NV_DL_RUN_UUID = "nv.dl.run.uuid"
NV_DL_SOFTWARE_CUDA = "nv.dl.software.cuda"
NV_DL_SOFTWARE_NCCL = "nv.dl.software.nccl"
NV_DL_SOFTWARE_TORCH = "nv.dl.software.torch"
NV_DL_SOFTWARE_TRANSFORMER_ENGINE = "nv.dl.software.transformer_engine"
NV_DL_TOPOLOGY_SIZE_DP = "nv.dl.topology.size.dp"
NV_DL_TOPOLOGY_SIZE_PP = "nv.dl.topology.size.pp"
NV_DL_TOPOLOGY_SIZE_TP = "nv.dl.topology.size.tp"
NV_DL_TRAINING_CONFIG_GLOBAL_BATCH_SIZE = "nv.dl.training.config.global_batch_size"
NV_DL_TRAINING_CONFIG_MICRO_BATCH_SIZE = "nv.dl.training.config.micro_batch_size"
NV_DL_TRAINING_CONFIG_OPTIMIZER = "nv.dl.training.config.optimizer"
NV_DL_TRAINING_CONFIG_RECOMPUTE_GRANULARITY = "nv.dl.training.config.recompute_granularity"
NV_DL_TRAINING_CONFIG_SEQUENCE_LENGTH = "nv.dl.training.config.sequence_length"
NV_DL_TRAINING_TARGET_TRAIN_ITERS = "nv.dl.training.target.train_iters"
NV_DL_TRAINING_TARGET_TRAIN_SAMPLES = "nv.dl.training.target.train_samples"
NV_DL_TRAINING_TARGET_TRAIN_TOKENS = "nv.dl.training.target.train_tokens"
NV_DL_WORLD_SIZE = "nv.dl.world_size"
NV_GPU_COMPUTE_CAPABILITY = "nv.gpu.compute_capability"
NV_GPU_DRIVER_VERSION = "nv.gpu.driver_version"
NV_GPU_INDEX = "nv.gpu.index"
NV_GPU_MEMORY_TOTAL = "nv.gpu.memory_total"
NV_GPU_MODEL = "nv.gpu.model"
NV_GPU_PCI_BUS_ID = "nv.gpu.pci_bus_id"
NV_GPU_SERIAL = "nv.gpu.serial"
NV_GPU_UUID = "nv.gpu.uuid"
RL_ALGORITHM = "rl.algorithm"
RL_GENERATION_BACKEND = "rl.generation.backend"
RL_NUM_ROLLOUTS = "rl.num_rollouts"
RL_REWARD = "rl.reward"
SLURM_ARRAY_COUNT = "slurm.array.count"
SLURM_ARRAY_JOB_ID = "slurm.array.job_id"
SLURM_ARRAY_SLUID = "slurm.array.sluid"
SLURM_ARRAY_TASK_ID = "slurm.array.task_id"
SLURM_CLUSTER = "slurm.cluster"
SLURM_CLUSTER_NAME = "slurm.cluster.name"
SLURM_HEAD_NODE_NAME = "slurm.head_node.name"
SLURM_JOB_ACCOUNT = "slurm.job.account"
SLURM_JOB_ID = "slurm.job.id"
SLURM_JOB_ID_RAW = "slurm.job.id.raw"
SLURM_JOB_NAME = "slurm.job.name"
SLURM_JOB_QOS = "slurm.job.qos"
SLURM_JOB_RESERVATION = "slurm.job.reservation"
SLURM_JOB_USER = "slurm.job.user"
SLURM_NNODES = "slurm.nnodes"
SLURM_NODELIST = "slurm.nodelist"
SLURM_NTASKS = "slurm.ntasks"
SLURM_PARTITION = "slurm.partition"
SLURM_RESTART_COUNT = "slurm.restart_count"
SLURM_SEGMENT = "slurm.segment"
SLURM_SLUID = "slurm.sluid"
SLURM_TOPOLOGY_ADDR = "slurm.topology.addr"
SLURM_TOPOLOGY_ADDR_PATTERN = "slurm.topology.addr_pattern"
SLURM_TORCHELASTIC_RESTART_COUNT = "slurm.torchelastic.restart_count"
WANDB_ENTITY = "wandb.entity"
WANDB_PROJECT = "wandb.project"
